language: c
 
git:
  depth: 300

install:
  - sudo add-apt-repository ppa:directhex/ppa -y
  - sudo apt-get update
  - sudo apt-get -qq install mono-devel mono-gmcs mono-utils mono-complete libmono-system2.0-cil libmono-corlib2.0-cil mono-2.0-gac nunit-console realpath
 
script:
  - export EnableNuGetPackageRestore=true
  - mozroots --import --sync
  - bash travis-ci/autoversion.sh JSONConfigHelpers
  - xbuild CI.proj
  - nunit-console ./JSONConfigurationHelpers.Test/bin/Debug/JSONConfigurationHelpers.Test.dll -exclude Integration,NotWorkingOnMono